@startuml
'!theme amiga
actor Бригадир
actor Сборщик
actor Кладовщик
participant Задание

== Создание заказа ==
activate Бригадир

create Задание
Бригадир -> Задание ++: "create" Создать Задание

== Назначение сборщика ==

Бригадир -> Сборщик --++: Назначить сборщика

Сборщик --> Бригадир: "return" Подтверждение назначения


== Сборка детали ==
Сборщик -> Задание : Проверить наличие комплектующих

Задание --> Сборщик: "return" Информация о наличии комплектующих

opt Есть Недостающие комплектующие

    create Кладовщик
    Сборщик -> Кладовщик ++ : Заказать недостающие комплектующие


    Кладовщик -> Сборщик : Уведомить о готовности комплектующих

    Кладовщик -> Сборщик --: Выдать комплектующие



end
    Сборщик -> Задание: Начать сборку детали
== Завершение сборки ==

    Задание -> Сборщик: Деталь собрана
	


Сборщик -> Бригадир --++: Информировать о готовности детали 

Бригадир -> Задание !!: "destroy" Закрыть Задание	
== Завершение заказа ==


@enduml

