@startuml
'!theme amiga
skinparam defaultFontSize 18

start

repeat :__Заказ__: Ждет исполнителя; <<task>>
repeat while (есть свободный сотрудник?) is (нет) not (да)
:обработать заказ();
:__Заказ__: Ожидание подтверждения; <<task>>
if (подтверждено?) then (да)
:__Заказ__ Подтвержден; <<task>>
:выполнить заказ();
:__Заказ__: Выполняется; <<task>>
:зафиксировать окончание();
:__Заказ__ Готов; <<task>>
:__Заказ__ Ожидание доставки; <<task>>
:отправить на выдачу();
repeat :уведомить о готовности();
:подождать 1 день;
if (пришел заказчик?) then (да)
	:выдать заказ();
	:__Заказ__ Исполнен; <<task>>
	stop
else (нет)
	endif
repeat while (прошло больше 10 дней?) is (нет) not (да)
:отменить выдачу();
:__Заказ__ Возврат на склад; <<task>>
:Расформировать заказ();
:__Заказ__ Отменен; <<task>>
else (нет)
:__Заказ__ Отменен; <<task>>
stop
endif

stop
@enduml
