@startuml
'!theme amiga
'!pragma layout smetana

skinparam ranksep 200
'top to bottom direction
'skinparam padding 20
skinparam DefaultFontSize 30
'skinparam ArrowFontSize 30

object Бригадир
object Сборщик
object Кладовщик
object Задание

Бригадир -[hidden]-> Сборщик
Сборщик -[hidden]-> Кладовщик
Кладовщик -[hidden]-> Задание

'== Создание и выполнение заказа ==

Бригадир --> Задание : 1.1: create Создать Задание
Бригадир --> Сборщик : 1.2: Назначить сборщика
Сборщик --> Бригадир : 2: Подтверждение назначения
Сборщик --> Задание : 3: Проверить наличие комплектующих
Задание --> Сборщик : 4: Информация о наличии

Сборщик --> Кладовщик : [нужны комплектующие] 5.1: Заказать недостающие
Кладовщик --> Сборщик : 5.2: Уведомить о готовности
Кладовщик --> Сборщик : 5.3: Выдать комплектующие

Сборщик --> Задание : 6: Начать сборку детали
Задание --> Сборщик : 7: Деталь собрана
Сборщик --> Бригадир : 8: Информировать о готовности
Бригадир --> Задание : 9: destroy Закрыть Задание
@enduml
