@startuml
'!theme amiga
skinparam defaultFontSize 18
[*] --> Ждет_исполнителя

Ждет_исполнителя --> Ожидание_подтверждения : обработать_заказ() [есть свободный сотрудник]

Ожидание_подтверждения --> Подтвержден : [подтверждено = true]
Ожидание_подтверждения --> Отменен : отменить_заказ() [подтверждено = false]
Отменен --> [*]

Подтвержден --> Выполнение_заказа : выполнить_заказ()
Выполнение_заказа --> Готов : зафиксировать_окончание()

Готов --> Ожидание_доставки : уведомить_о_готовности()
Ожидание_доставки --> Ожидание_выдачи : отправить_на_выдачу()

state Ожидание_выдачи {
	Ожидание_выдачи : entry / уведомить_о_готовности()
}

Ожидание_выдачи --> Ожидание_выдачи : прошел 1 день
Ожидание_выдачи --> Возврат_на_склад : отменить_выдачу() [прошло больше 10 дней]
Ожидание_выдачи --> Завершен : выдать_заказ() [пришел заказчик (сборщик)]

Возврат_на_склад --> Ожидание_доставки : вернуть_на_склад()

Завершен --> [*]

/'
 ' В_процессе --> Ждет_исполнителя : обновить_статус() [статус != "готов"]
 '/
@enduml
